### ISSUE TITLE
random.h messed up

### ISSUE THREAD

**Issue by lonnietc** [XDU-SysSec/RansomTag#2]
Hello, 

I could not get it to compile on Ubuntu 22.04 (x64) as it seems that your "drivers/usb/randomtag.h" is really mixed up and I have not been able to  sort through it yet.

```
RansomTag/test/01.Detection modules$ make
case "`sed 1q ./.depends 2>/dev/null`" in \
''): >> ./.depends;; esac
make -s -f Makefile.build build-dir DIR=. V=0
  CC core/main.o
In file included from core/main.c:65:
core/../drivers/usb/ransomtag.h:1: error: unterminated #ifndef
    1 | #ifndef _RANSOMTAG_H
      |
core/main.c: In function ‘print_boot_msg’:
core/main.c:84:5: warning: implicit declaration of function ‘win_ransomtag_init’ [-Wimplicit-function-declaration]
   84 |     win_ransomtag_init();      //ransomtag
      |     ^~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile.build:145: core/main.o] Error 1
make[1]: *** [Makefile.build:136: core/output.o_p] Error 2
make: *** [Makefile:43: build-all] Error 2
```

**Comment by lonnietc** [comment]
Hello, 

Is there any update on this as I cannot get it to compile give the problems within the code base right now?

Thanks and have a great day

**Comment by lonnietc** [comment]
In more review of the code base, it looks like you have lost add of your link file information in the openssl and there may be other issues also.

Can you please zip of a working version and put it on your release page so that I can get it and give it a try on my Ubuntu 22.04 (x64)?

Also, what version of Bitvisor did you use as well since the latest is v3.0 that also has Wireguard integrated as well:

```
https://github.com/matsu/bitvisor
```

Thanks again

**Comment by lonnietc** [comment]
Any updates on this?
